### ISSUE TITLE
[Question] How do you plan to store the user's keyword list?

### ISSUE THREAD

**Issue by longnd** [kokomyoheinhtet/kookle#3]
As the logic to handle the uploaded keyword file was not completed, I would like to understand how you plan to design the DB schema to store the uploaded keywords.

**Comment by kokomyoheinhtet** [comment]
So, here is my plan how to query the data.

![image](https://github.com/kokomyoheinhtet/kookle/assets/30713714/818fca42-5580-46fa-b3df-8673336d6ed9)

As for the DB Schema, I designed as below. Please kindly review and give some feedback.
![image](https://github.com/kokomyoheinhtet/kookle/assets/30713714/d8b754e6-4eb9-410f-b51d-50ef509e3e5d)

**Comment by longnd** [comment]
There is an issue with the proposed solution: the DB design does not allow scoping the keywords by users (in the `keywords` table), which means any user will have access to all keywords uploaded by other users.

**Comment by kokomyoheinhtet** [comment]
I apologize I misunderstood that the task. Initially, I understood that only authenticated users can access the list.

In this case, I think by adding the following 2 steps could improve.
1. add `user_id` from user table as foreign key
2. add `user_id` to cache when user upload the file

Please give me a feedback on what you think.
