### ISSUE TITLE
[Question] What is the plan to process the uploaded keyword list?

### ISSUE THREAD

**Issue by longnd** [kokomyoheinhtet/kookle#4]
While it has not been implemented yet, I would like to understand how you plan to process the uploaded keyword list to scrap the result from Google Search and workaround Google Rate Limiting. Could you please share the implementation approach?
What will happen after the CSV file is uploaded to Firebase storage?

**Comment by kokomyoheinhtet** [comment]
This is the next step to implement the requirement
![image](https://github.com/kokomyoheinhtet/kookle/assets/30713714/734fb14b-4f6a-4d62-8aeb-ef89582a0213)

As for the Google Rate Limiting limitation, I would like to introduce the following improved solution. 
I add cache to store the keywords temporarily as a queue(we can also introduce pub/sub systems such as kafka)
![image](https://github.com/kokomyoheinhtet/kookle/assets/30713714/76a46af7-b604-441c-a115-acd43a989580)

**Comment by longnd** [comment]
Thank you for sharing your approach, I appreciate the time and effort you put on this.
IMO, the solution to workaround Google rate limit by adding a break (10 seconds) between requests isn't efficient as Google can still block suspicious requests if they come from the same IP. Some other alternatives include rotating the user Agent or using a different proxy for the scrapping requests.

**Comment by kokomyoheinhtet** [comment]
That is such a great idea. I have never deal with rate limiting  api, so, my initial approach was not completed. But, your suggestion made it better. I will keep that in mind and I can apply it in my future projects.
